### ISSUE TITLE
OpenADR 3.0.1 support

### ISSUE THREAD

**Issue by philippbruhin** [robogeek/nodeadr#10]
Dear @robogeek,

Thank you for sharing this repository with the world. May I ask if it is actively used and under development on your side? Is support for OpenADR 3.0.1 planned for this repository, or do you know of any other TypeScript repositories that support OpenADR 3.0?

Thanks, Phil

**Comment by robogeek** [comment]
This repository implements OpenADR 2.0b which is extremely different from 3.0.x.  I wrote this as an exercise before I joined the 3.0.x team last year.  I actually got rather confused by 2.0b and never got this to run for more than a fraction of OpenADR 2.0 features.

I have implemented a full VTN for OpenADR 3.0 in Node.js/TypeScript.  But, the client does not want that code to be released at this time.  You can see marketing information about that project at https://esx.energy -- In the background of that is an OpenADR 3 VTN implemented in Node.js/TypeScript, and it is processing live information from the EV charging network operated by Evoke Systems. 

Most of the people working on 3.0.x seem to be Python users rather than Node.js/TypeScript.  So far as I can tell from participating with 3.0.x work for over a year, I'm the only one who mentioned Node.js/TypeScript in any meetings.

The only code I've been able to release is a set of type declarations and data validation code for OpenADR 3 objects.

https://github.com/clean-energy-tools/openadr-3-ts-types

I have an unfinished project which I'll be able to release.

**Comment by philippbruhin** [comment]
Thank you very much, @robogeek for your appreciated and helpful feedback. The marketing information at [esx.energy](https://esx.energy) has already helped me understand the entire system better. I'm quite new to this topic, and unfortunately, OpenADR is still hardly used here in Switzerland. It should be noted that we have an oversized and well-maintained power grid in many places here. However, electromobility and decentralized energy generation will present challenges for us.

I look forward to hearing from you regarding your upcoming project that you will release. I am very curious.

**Comment by robogeek** [comment]
It is certainly possible for Switzerland to adopt OpenADR.  There is development work happening in several countries outside the USA, so it is not a solely American thing.  The ESX team has had discussions with folks in Norway & Sweden.

**Comment by philippbruhin** [comment]
May I ask if there is any chance to contact you for a short meeting regarding OpenADR?

**Comment by robogeek** [comment]
I sent a response via DM on Twitter.  Did you see it?
